use ats;
DROP TABLE TEST_STEP_DATA_MAPPING;
DROP TABLE TEST_EXPECTED_RES_MAPPING;
DROP TABLE TEST_CASE_STEPS_MAPPING;
DROP TABLE TEST_STEP_DATA;
DROP TABLE TEST_EXPECTED_RES;
DROP TABLE TEST_CASE_STEPS;
DROP TABLE TEST_CASES;