use ats; 
CREATE TABLE TEST_STEP_DATA_MAPPING (
	TEST_STEP_ID	INTEGER		NOT NULL ,	
	TEST_DATA_ID	INTEGER 	NOT NULL ,
	ORD 			INTEGER			NULL ,
	CONSTRAINT pk_TEST_STEP_DATA_MAPPING PRIMARY KEY (TEST_STEP_ID, TEST_DATA_ID),
	CONSTRAINT fk1_TEST_STEP_DATA_MAPPING FOREIGN KEY (TEST_STEP_ID) REFERENCES TEST_CASE_STEPS(ID),
	CONSTRAINT fk2_TEST_STEP_DATA_MAPPING FOREIGN KEY (TEST_DATA_ID) REFERENCES TEST_STEP_DATA(ID)
);