use ats;
CREATE TABLE TEST_EXPECTED_RES_MAPPING ( 
	TEST_STEP_ID	INTEGER		NOT NULL ,	
	TEST_EXP_RES_ID	INTEGER 	NOT NULL ,
	ORD 			INTEGER			NULL,
	CONSTRAINT pk1_TEST_EXPECTED_RES_MAPPING PRIMARY KEY (TEST_STEP_ID, TEST_EXP_RES_ID),
	CONSTRAINT fk1_TEST_EXPECTED_RES_MAPPING FOREIGN KEY (TEST_STEP_ID) 	REFERENCES TEST_CASE_STEPS(ID),
	CONSTRAINT fk2_TEST_EXPECTED_RES_MAPPING FOREIGN KEY (TEST_EXP_RES_ID) 	REFERENCES TEST_EXPECTED_RES(ID)
) ;