use ats;
CREATE TABLE TEST_STEP_DATA ( 
	ID 						INTEGER 		NOT NULL AUTO_INCREMENT,
	ELEMENT_NAME			VARCHAR(300)	NULL,
	ELEMENT_TYPE 			VARCHAR(100)	NOT NULL,
	VALUE					VARCHAR(1000)	NULL,
	LOCATION_XPATH			VARCHAR(1000)	NOT NULL,
	ACTION					VARCHAR(300)	NOT NULL,
	CONSTRAINT	TEST_STEP_DATA_pk1	PRIMARY KEY (ID) 
);