use ats;
CREATE TABLE TEST_CASE_STEPS_MAPPING (
	TEST_ID INTEGER NOT NULL,
	TEST_STEP_ID INTEGER NOT NULL,	
	ORD 	INTEGER NOT NULL,
	CONSTRAINT TEST_CASE_STEPS_MAPPING_PK PRIMARY KEY (TEST_ID, TEST_STEP_ID),
	CONSTRAINT fk1_TEST_CASE_STEPS_MAPPING FOREIGN KEY (TEST_ID) REFERENCES TEST_CASES(ID),
	CONSTRAINT fk2_TEST_CASE_STEPS_MAPPING FOREIGN KEY (TEST_STEP_ID) REFERENCES TEST_CASE_STEPS(ID)
);
