use ats;
CREATE TABLE TEST_EXPECTED_RES ( 
	ID				INTEGER 		NOT NULL 	AUTO_INCREMENT,
	ELEMENT_NAME 	VARCHAR(300)		NULL,
	ELEMENT_TYPE	VARCHAR(300)	NOT NULL,
	LOCATION_XPATH	VARCHAR(1000)	NOT NULL,
	VALUE			VARCHAR(1000)	NOT NULL,
	CONSTRAINT	TEST_EXPECTED_RES_pk PRIMARY KEY(ID)  
); 