use ats;
CREATE TABLE TEST_CASE_STEPS (
		ID 		INTEGER 		NOT NULL AUTO_INCREMENT,
	NAME	VARCHAR(300)	NOT NULL,
	DESCRIPTION 	VARCHAR(300),	
	CONSTRAINT TEST_CASE_STEPS_PK PRIMARY KEY (ID)
);
commit;